### PR TITLE
[GH-47]Add autocomplete icon

### LINKED ISSUE #47: Add autocomplete icon
Since v5.24 slash commands can provide an `svg` via  `AutocompleteIconData` in `model.Command` that is then shown in the autocomplete list. This ticket is about adding the icon in `assets` to the slash command.

Include screenhots from a dark and a bright theme in the PR description, as there might be the need for a separate icon with a white background for autocomplete.

Similar PRs:
For GitHub plugin https://github.com/mattermost/mattermost-plugin-github/pull/359
For Jira plugin https://github.com/mattermost/mattermost-plugin-jira/pull/653

### PR DESCRIPTION
**Pull request by ByeongsuPark**
#### Summary

Screenshot_2020-10-15_18-20-40
Screenshot_2020-10-15_18-20-15
Add autocomplete icon
#### Ticket link

Fixes #47

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Awesome :rocket:

**Review by cpoile — APPROVED** [review]
Nice, thanks @ByeongsuPark!

**Comment by ByeongsuPark** [comment]
Sorry. I accidentally close this so I reopend it.

**Comment by hanzei** [comment]
@DHaussermann This might be a good one for dev testing

**Comment by DHaussermann** [comment]
@hanzei or @cpoile  If you have a bit of time, could one of you peer-test this PR using the  peer testing process documented here https://mattermost.atlassian.net/wiki/spaces/INT/pages/619937892/Peer+Testing+Process

**Review by hanzei — APPROVED** [review]
Tested on dark and bright theme. Icon looks good in both themes.

**Comment by hanzei** [comment]
Thanks for the contribution @ByeongsuPark :+1:

**Pull request merged**
