### PR TITLE
[MM-109] Update plugin with respect to phase 1 upgrades

### PR DESCRIPTION
**Pull request by ayusht2810**
#### Summary
Updated plugin with respect to phase 1 upgrades

- Updated build folder
- Updated Makefile
- Updated version in `nvmrc` file and updated `package-lock.json` file.
- Added webapp base setup for test cases.
- Added webapp base setup for typescript.
- Updated developer docs link in the readme file 
- Updated package in go modules to use https://pkg.go.dev/github.com/mattermost/mattermost/server/public.
- Fixed server test cases and added a webapp test case.

#### Ticket Link

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
I'm approving, assuming the changes are in line with our standards for plugins (@mickmister ?).

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
Waiting on https://github.com/mattermost/mattermost-plugin-welcomebot/pull/123#issuecomment-1945374716 before merging

**Comment by mickmister** [comment]
@ayusht2810 Can you please run the CI commands locally?

**Comment by Kshitij-Katiyar** [comment]
> @ayusht2810 Can you please run the CI commands locally?

@mickmister I ran the CI commands locally and found some lint errors which I have fixed as well.

**Review by mickmister — APPROVED** [review]

**Pull request merged**
