### PR TITLE
Updated docs from Gitbook

### PR DESCRIPTION
**Pull request by aaronrothschild**
Check this out too - it's the same docs but hosted in GitBook:  https://aaron-rothschild.gitbook.io/webex-plugin/settings-for-webex

### CODE REVIEW

**Comment by aaronrothschild** [comment]
@cpoile It shouldn't be blank, It seems to have disappeared.  I actually added some extra links and context to that area so it's more descriptive and gives hints on where to go.

**Comment by cpoile** [comment]
@aaronrothschild Ok, I see it in the code, but not the gitbook. So, how important is the gitbook for this PR? Is it a blocking problem, or just a bit of weirdness?

**Comment by aaronrothschild** [comment]
> @aaronrothschild Ok, I see it in the code, but not the gitbook. So, how important is the gitbook for this PR? Is it a blocking problem, or just a bit of weirdness?

@cpoile Just a bit of weirdness.  I kept the Readme.MD file so the docs are there either way.  I'm trying to sort out gitbook licencing, etc.

**Comment by cpoile** [comment]
Cool. Waiting on @DHaussermann then for his go over and editing advice. Thanks @aaronrothschild !

**Pull request merged**
