### PR TITLE
Add a settings to control URL substitution

### LINKED ISSUE #31: Use different URL to achieve linux compatibility
Hi,
when using a linux browser webex throws the following error on /join and /start urls:
```
Sie können dieses Webex-Meeting nicht starten bzw. ihm beitreten, weil es für Webex Meetings-Videokonferenzen aktiviert ist. Diese Funktion wird von Ihrem Browser, Ihrer Browserversion oder Ihrem Betriebssystem nicht unterstützt. Wenden Sie sich an Ihren Administrator, um weitere Informationen zu erhalten.
```
Which is translated something like this:
```
You cannot start or join this Webex meeting because it is enabled for Webex meetings video conferencing. This feature is not supported by your browser, browser version, or operating system. Contact your administrator for more information.
```
How about we post links like this https://site.webex.com/meet/room_name that should work also on linux.

Kind regards,
Centzilius

### PR DESCRIPTION
**Pull request by gbonnefille**
#### Summary
This substitution is known to break Linux experience.
While the raw URL is also known to work on Windows.

In some circumstance, it could be desirable to not substitute
URLs.

#### Ticket Link
Fixes #31

### CODE REVIEW

**Comment by gbonnefille** [comment]
Feel free to pick ideas from this proposed solution instead of merging it directly.

**Review by cpoile — APPROVED** [review]
Thanks @gbonnefille !

**Comment by cpoile** [comment]
@DHaussermann Are you able to test on windows, mac, and linux, and do we still have a Webex account to test with?

**Review by DHaussermann — APPROVED** [review]

**Comment by jasonblais** [comment]
@cpoile looks like this would be ready to merge?

**Comment by larkox** [comment]
@jasonblais This is having some ci issues (some test are failing), so we shoulnd't merge yet.
@gbonnefille could you look at the tests and fix them?

**Comment by gbonnefille** [comment]
> @jasonblais This is having some ci issues (some test are failing), so we shoulnd't merge yet.
> @gbonnefille could you look at the tests and fix them?

I'm strictly unable to investigate on these failures.

**Comment by cpoile** [comment]
@gbonnefille Could you click the `Allow edits from maintainers` button please? Then I'll fix the tests.

For more info, see: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by gbonnefille** [comment]
> @gbonnefille Could you click the `Allow edits from maintainers` button please? Then I'll fix the tests.
> 
> For more info, see: https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

As far as I understand Github, it is already checked.
image

**Comment by hanzei** [comment]
@gbonnefille I've fixed the test for you so we can merge this PR. Thanks for the contribution! :tada:

**Comment by gbonnefille** [comment]
> @gbonnefille I've fixed the test for you so we can merge this PR. Thanks for the contribution! tada

Many thanks!

**Pull request merged**
